# Site settings
title: AlanViast
email: AlanViast@Gmail.com
description: "AlanViast 的个人博客"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alanviast.github.io" # the base hostname & protocol for your site
github_username:  AlanViast


constant:
    delimiter: "~"

sass:
    sass_dir: /assets/stylesheets/

javascript:
    javascript_dir: /assets/javascripts/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
