# Site settings
title: AlanViast
email: AlanViast@Gmail.com
description: "AlanViast 的个人博客"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alanviast.github.io" # the base hostname & protocol for your site
github_username:  AlanViast

# Build settings
markdown: kramdown
